// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

void Vtop___024root____Vdpiexp_top__DOT__clkg__DOT__toggleClock_TOP(Vtop__Syms* __restrict vlSymsp);

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{
}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-12);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_top.configure(this, name(), "top", "top", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__clkg.configure(this, name(), "top.clkg", "clkg", -12, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__dut.configure(this, name(), "top.dut", "dut", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__dut__core.configure(this, name(), "top.dut.core", "core", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__dut__core__al1.configure(this, name(), "top.dut.core.al1", "al1", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__dut__core__bc1.configure(this, name(), "top.dut.core.bc1", "bc1", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__dut__core__cs1.configure(this, name(), "top.dut.core.cs1", "cs1", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__dut__core__dec1.configure(this, name(), "top.dut.core.dec1", "dec1", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__dut__core__dmem1.configure(this, name(), "top.dut.core.dmem1", "dmem1", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__dut__core__imem1.configure(this, name(), "top.dut.core.imem1", "imem1", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__dut__core__rf1.configure(this, name(), "top.dut.core.rf1", "rf1", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__dut__core__wb1.configure(this, name(), "top.dut.core.wb1", "wb1", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_top__genblk1.configure(this, name(), "top.genblk1", "genblk1", 0, VerilatedScope::SCOPE_OTHER);
    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_top__clkg.exportInsert(__Vfinal, "toggleClock", (void*)(&Vtop___024root____Vdpiexp_top__DOT__clkg__DOT__toggleClock_TOP));
        __Vscope_top.varInsert(__Vfinal,"clock", &(TOP.top__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top.varInsert(__Vfinal,"reset", &(TOP.top__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__clkg.varInsert(__Vfinal,"clk", &(TOP.top__DOT__clkg__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__clkg.varInsert(__Vfinal,"counter", &(TOP.top__DOT__clkg__DOT__counter), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__clkg.varInsert(__Vfinal,"rst", &(TOP.top__DOT__clkg__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut.varInsert(__Vfinal,"clock", &(TOP.top__DOT__dut__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut.varInsert(__Vfinal,"reset", &(TOP.top__DOT__dut__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"ADDRW", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__ADDRW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"BASE_ADDR", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__BASE_ADDR))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"BRANCH_OPCODE", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__BRANCH_OPCODE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"BYTE_OP", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__BYTE_OP))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"DATAW", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__DATAW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"ECALL_OPCODE", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__ECALL_OPCODE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"HALF_OP", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__HALF_OP))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"IMM", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__IMM))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"LOAD_OPCODE", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__LOAD_OPCODE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"MX_BYPASS", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__MX_BYPASS))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"NOP_INSTR", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__NOP_INSTR))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"NOP_OPCODE", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__NOP_OPCODE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"N_BITS", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__N_BITS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"PC", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__PC))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"REG", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__REG))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"STORE_OPCODE", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__STORE_OPCODE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"WORD_OP", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__WORD_OP))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"WX_BYPASS", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__WX_BYPASS))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"a_sel", &(TOP.top__DOT__dut__DOT__core__DOT__a_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"addr_rd_dx_r", &(TOP.top__DOT__dut__DOT__core__DOT__addr_rd_dx_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"addr_rd_mw_r", &(TOP.top__DOT__dut__DOT__core__DOT__addr_rd_mw_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"addr_rd_w", &(TOP.top__DOT__dut__DOT__core__DOT__addr_rd_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"addr_rd_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__addr_rd_xm_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"addr_rs1_dx_r", &(TOP.top__DOT__dut__DOT__core__DOT__addr_rs1_dx_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"addr_rs1_w", &(TOP.top__DOT__dut__DOT__core__DOT__addr_rs1_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"addr_rs2_dx_r", &(TOP.top__DOT__dut__DOT__core__DOT__addr_rs2_dx_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"addr_rs2_w", &(TOP.top__DOT__dut__DOT__core__DOT__addr_rs2_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"addr_rs2_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__addr_rs2_xm_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"alu_in1_w", &(TOP.top__DOT__dut__DOT__core__DOT__alu_in1_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"alu_in2_w", &(TOP.top__DOT__dut__DOT__core__DOT__alu_in2_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"alu_mw_r", &(TOP.top__DOT__dut__DOT__core__DOT__alu_mw_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"alu_out_w", &(TOP.top__DOT__dut__DOT__core__DOT__alu_out_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"alu_sel", &(TOP.top__DOT__dut__DOT__core__DOT__alu_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"alu_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__alu_xm_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"b_sel", &(TOP.top__DOT__dut__DOT__core__DOT__b_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"br_eq", &(TOP.top__DOT__dut__DOT__core__DOT__br_eq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"br_lt", &(TOP.top__DOT__dut__DOT__core__DOT__br_lt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"br_taken", &(TOP.top__DOT__dut__DOT__core__DOT__br_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"br_un", &(TOP.top__DOT__dut__DOT__core__DOT__br_un), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"branch_comp_data1_sel", &(TOP.top__DOT__dut__DOT__core__DOT__branch_comp_data1_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"branch_comp_data2_sel", &(TOP.top__DOT__dut__DOT__core__DOT__branch_comp_data2_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"clock", &(TOP.top__DOT__dut__DOT__core__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"data_mem_rw", &(TOP.top__DOT__dut__DOT__core__DOT__data_mem_rw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"data_mem_w", &(TOP.top__DOT__dut__DOT__core__DOT__data_mem_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"data_mem_w_sized", &(TOP.top__DOT__dut__DOT__core__DOT__data_mem_w_sized), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"data_rd_w", &(TOP.top__DOT__dut__DOT__core__DOT__data_rd_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"data_rs1_stall_w", &(TOP.top__DOT__dut__DOT__core__DOT__data_rs1_stall_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"data_rs1_w", &(TOP.top__DOT__dut__DOT__core__DOT__data_rs1_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"data_rs2_stall_w", &(TOP.top__DOT__dut__DOT__core__DOT__data_rs2_stall_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"data_rs2_w", &(TOP.top__DOT__dut__DOT__core__DOT__data_rs2_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"data_rs2_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__data_rs2_xm_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"dmem_data_in", &(TOP.top__DOT__dut__DOT__core__DOT__dmem_data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"dx_en", &(TOP.top__DOT__dut__DOT__core__DOT__dx_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"fd_en", &(TOP.top__DOT__dut__DOT__core__DOT__fd_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"fetch_en", &(TOP.top__DOT__dut__DOT__core__DOT__fetch_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"funct3_dx_r", &(TOP.top__DOT__dut__DOT__core__DOT__funct3_dx_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"funct3_mw_r", &(TOP.top__DOT__dut__DOT__core__DOT__funct3_mw_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"funct3_w", &(TOP.top__DOT__dut__DOT__core__DOT__funct3_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"funct3_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__funct3_xm_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"funct7_dx_r", &(TOP.top__DOT__dut__DOT__core__DOT__funct7_dx_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"funct7_w", &(TOP.top__DOT__dut__DOT__core__DOT__funct7_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"idata1_in", &(TOP.top__DOT__dut__DOT__core__DOT__idata1_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"idata2_in", &(TOP.top__DOT__dut__DOT__core__DOT__idata2_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"imem_enable", &(TOP.top__DOT__dut__DOT__core__DOT__imem_enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"imem_in_r", &(TOP.top__DOT__dut__DOT__core__DOT__imem_in_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"imem_rw_w", &(TOP.top__DOT__dut__DOT__core__DOT__imem_rw_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"imm_dx_r", &(TOP.top__DOT__dut__DOT__core__DOT__imm_dx_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"imm_w", &(TOP.top__DOT__dut__DOT__core__DOT__imm_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"imm_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__imm_xm_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"instr_fd_w", &(TOP.top__DOT__dut__DOT__core__DOT__instr_fd_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"instr_mw_writes_reg", &(TOP.top__DOT__dut__DOT__core__DOT__instr_mw_writes_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"instr_w", &(TOP.top__DOT__dut__DOT__core__DOT__instr_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"instr_xm_writes_reg", &(TOP.top__DOT__dut__DOT__core__DOT__instr_xm_writes_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"is_i_type", &(TOP.top__DOT__dut__DOT__core__DOT__is_i_type), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"is_j_type", &(TOP.top__DOT__dut__DOT__core__DOT__is_j_type), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"is_load_dx", &(TOP.top__DOT__dut__DOT__core__DOT__is_load_dx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"is_load_xm", &(TOP.top__DOT__dut__DOT__core__DOT__is_load_xm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"is_nop_mw", &(TOP.top__DOT__dut__DOT__core__DOT__is_nop_mw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"is_nop_xm", &(TOP.top__DOT__dut__DOT__core__DOT__is_nop_xm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"is_store_fd", &(TOP.top__DOT__dut__DOT__core__DOT__is_store_fd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"is_store_xm", &(TOP.top__DOT__dut__DOT__core__DOT__is_store_xm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"is_u_type", &(TOP.top__DOT__dut__DOT__core__DOT__is_u_type), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"is_unsigned", &(TOP.top__DOT__dut__DOT__core__DOT__is_unsigned), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"load_stall", &(TOP.top__DOT__dut__DOT__core__DOT__load_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"load_store_stall", &(TOP.top__DOT__dut__DOT__core__DOT__load_store_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"mem_read_access_size", &(TOP.top__DOT__dut__DOT__core__DOT__mem_read_access_size), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"mem_write_access_size", &(TOP.top__DOT__dut__DOT__core__DOT__mem_write_access_size), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"mw_en", &(TOP.top__DOT__dut__DOT__core__DOT__mw_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"opcode_dx_r", &(TOP.top__DOT__dut__DOT__core__DOT__opcode_dx_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"opcode_mw_r", &(TOP.top__DOT__dut__DOT__core__DOT__opcode_mw_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"opcode_w", &(TOP.top__DOT__dut__DOT__core__DOT__opcode_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"opcode_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__opcode_xm_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"pc4_f_w", &(TOP.top__DOT__dut__DOT__core__DOT__pc4_f_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"pc4_mw_r", &(TOP.top__DOT__dut__DOT__core__DOT__pc4_mw_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"pc4_xm_w", &(TOP.top__DOT__dut__DOT__core__DOT__pc4_xm_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"pc_dx_r", &(TOP.top__DOT__dut__DOT__core__DOT__pc_dx_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"pc_fd_r", &(TOP.top__DOT__dut__DOT__core__DOT__pc_fd_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"pc_mw_r", &(TOP.top__DOT__dut__DOT__core__DOT__pc_mw_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"pc_r", &(TOP.top__DOT__dut__DOT__core__DOT__pc_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"pc_sel", &(TOP.top__DOT__dut__DOT__core__DOT__pc_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"pc_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__pc_xm_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"prev_instr", &(TOP.top__DOT__dut__DOT__core__DOT__prev_instr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"reg_wen", &(TOP.top__DOT__dut__DOT__core__DOT__reg_wen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"reset", &(TOP.top__DOT__dut__DOT__core__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"shamt_w", &(TOP.top__DOT__dut__DOT__core__DOT__shamt_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"stall", &(TOP.top__DOT__dut__DOT__core__DOT__stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"stall_fd", &(TOP.top__DOT__dut__DOT__core__DOT__stall_fd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"store_rs2_stall", &(TOP.top__DOT__dut__DOT__core__DOT__store_rs2_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"wb_sel", &(TOP.top__DOT__dut__DOT__core__DOT__wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"wd_stall", &(TOP.top__DOT__dut__DOT__core__DOT__wd_stall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"wm_forward", &(TOP.top__DOT__dut__DOT__core__DOT__wm_forward), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core.varInsert(__Vfinal,"xm_en", &(TOP.top__DOT__dut__DOT__core__DOT__xm_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"ADD", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__ADD))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"AND", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__AND))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"DIV", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__DIV))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"DIVU", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__DIVU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"IDATAW", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__IDATAW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"MUL", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__MUL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"NOP", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__NOP))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"ODATAW", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__ODATAW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"OR", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__OR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"SLL", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__SLL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"SLT", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__SLT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"SLTU", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__SLTU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"SRA", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__SRA))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"SRL", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__SRL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"SUB", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__SUB))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"XOR", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__XOR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"alu_sel", &(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__alu_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"idata1", &(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__idata1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"idata2", &(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__idata2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"mask", &(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__mask), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__al1.varInsert(__Vfinal,"odata", &(TOP.top__DOT__dut__DOT__core__DOT__al1__DOT__odata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__bc1.varInsert(__Vfinal,"IDATAW", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__bc1__DOT__IDATAW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__bc1.varInsert(__Vfinal,"br_eq", &(TOP.top__DOT__dut__DOT__core__DOT__bc1__DOT__br_eq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__bc1.varInsert(__Vfinal,"br_lt", &(TOP.top__DOT__dut__DOT__core__DOT__bc1__DOT__br_lt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__bc1.varInsert(__Vfinal,"br_un", &(TOP.top__DOT__dut__DOT__core__DOT__bc1__DOT__br_un), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__bc1.varInsert(__Vfinal,"idata1", &(TOP.top__DOT__dut__DOT__core__DOT__bc1__DOT__idata1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__bc1.varInsert(__Vfinal,"idata2", &(TOP.top__DOT__dut__DOT__core__DOT__bc1__DOT__idata2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"ADD", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__ADD))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"ADDRW", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__ADDRW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"AND", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__AND))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"DATAW", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__DATAW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"DIV", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__DIV))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"DIVU", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__DIVU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"IMM", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__IMM))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"MUL", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__MUL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"MX_BYPASS", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__MX_BYPASS))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"NOP", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__NOP))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"OR", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__OR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"PC", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__PC))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"REG", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__REG))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"SLL", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__SLL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"SLT", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__SLT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"SLTU", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__SLTU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"SRA", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__SRA))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"SRL", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__SRL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"SUB", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__SUB))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"WB_ALU", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__WB_ALU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"WB_MEM", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__WB_MEM))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"WB_PC4", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__WB_PC4))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"WX_BYPASS", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__WX_BYPASS))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"XOR", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__XOR))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"a_sel", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__a_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"addr_rd_mw", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rd_mw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"addr_rd_xm", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rd_xm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"addr_rs1_dx", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rs1_dx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"addr_rs2_dx", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rs2_dx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"alu_sel", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__alu_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"b_sel", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__b_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"br_eq", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__br_eq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"br_lt", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__br_lt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"br_taken", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__br_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"br_un", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__br_un), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"branch_comp_data1_sel", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__branch_comp_data1_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"branch_comp_data2_sel", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__branch_comp_data2_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"branch_taken", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__branch_taken), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"clock", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"dx_en", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__dx_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"funct3", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"funct7", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__funct7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"insn_mw_writes_reg", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__insn_mw_writes_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"insn_xm_writes_reg", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__insn_xm_writes_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_alu_imm_x", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_alu_imm_x), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_alu_x", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_alu_x), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_auipc_x", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_auipc_x), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_branch_mw_r", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_branch_mw_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_branch_x", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_branch_x), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_branch_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_branch_xm_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_ecall_mw_r", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_mw_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_ecall_wb", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_wb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_ecall_x", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_x), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_ecall_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_xm_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_jal_mw_r", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jal_mw_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_jal_x", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jal_x), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_jal_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jal_xm_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_jalr_mw_r", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jalr_mw_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_jalr_x", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jalr_x), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_jalr_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jalr_xm_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_load_mw_r", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_load_mw_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_load_x", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_load_x), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_load_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_load_xm_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_lui_x", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_lui_x), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_nop", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_nop), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_store_mw_r", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_store_mw_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_store_x", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_store_x), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_store_xm_r", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_store_xm_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"is_u_type_x", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__is_u_type_x), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"mem_rw", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__mem_rw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"mw_en", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__mw_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"opcode_dx", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__opcode_dx), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"opcode_mw", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__opcode_mw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"opcode_xm", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__opcode_xm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"pc_sel", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__pc_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"reg_wen", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__reg_wen), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"reset", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__reset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"wb_sel", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__cs1.varInsert(__Vfinal,"xm_en", &(TOP.top__DOT__dut__DOT__core__DOT__cs1__DOT__xm_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"ADDRW", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__ADDRW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"DATAW", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__DATAW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"IMM_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__IMM_SIZE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"IMM_UJ_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__IMM_UJ_SIZE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"N_BITS", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__N_BITS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"_funct3", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT___funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"_funct7", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT___funct7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"_imm_b", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT___imm_b), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"_imm_i", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT___imm_i), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"_imm_j", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT___imm_j), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,19,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"_imm_s", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT___imm_s), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"_imm_u", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT___imm_u), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,19,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"_opcode", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT___opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"_rd", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT___rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"_rs1", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT___rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"_rs2", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT___rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"addr_rd", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__addr_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"addr_rs1", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__addr_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"addr_rs2", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__addr_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"funct3", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__funct3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"funct7", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__funct7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"imm", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"instr", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__instr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_alu", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_alu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_alu_imm", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_alu_imm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_auipc", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_auipc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_b_type", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_b_type), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_branch", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_ecall", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_ecall), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_i_shift", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_i_shift), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_i_type", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_i_type), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_i_type_w", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_i_type_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_j_type", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_j_type), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_j_type_w", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_j_type_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_jal", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_jalr", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_load", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_load), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_lui", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_lui), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_r_type", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_r_type), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_s_type", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_s_type), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_store", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_store), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_u_type", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_u_type), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"is_u_type_w", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__is_u_type_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"opcode", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_top__dut__core__dec1.varInsert(__Vfinal,"shamt", &(TOP.top__DOT__dut__DOT__core__DOT__dec1__DOT__shamt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__dmem1.varInsert(__Vfinal,"BASE", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__dmem1__DOT__BASE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dmem1.varInsert(__Vfinal,"access_size", &(TOP.top__DOT__dut__DOT__core__DOT__dmem1__DOT__access_size), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__dmem1.varInsert(__Vfinal,"addr", &(TOP.top__DOT__dut__DOT__core__DOT__dmem1__DOT__addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dmem1.varInsert(__Vfinal,"address", &(TOP.top__DOT__dut__DOT__core__DOT__dmem1__DOT__address), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dmem1.varInsert(__Vfinal,"clock", &(TOP.top__DOT__dut__DOT__core__DOT__dmem1__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dmem1.varInsert(__Vfinal,"data_in", &(TOP.top__DOT__dut__DOT__core__DOT__dmem1__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dmem1.varInsert(__Vfinal,"data_out", &(TOP.top__DOT__dut__DOT__core__DOT__dmem1__DOT__data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dmem1.varInsert(__Vfinal,"i", &(TOP.top__DOT__dut__DOT__core__DOT__dmem1__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__dmem1.varInsert(__Vfinal,"mem", &(TOP.top__DOT__dut__DOT__core__DOT__dmem1__DOT__mem), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,2 ,7,0 ,0,1048575);
        __Vscope_top__dut__core__dmem1.varInsert(__Vfinal,"read_write", &(TOP.top__DOT__dut__DOT__core__DOT__dmem1__DOT__read_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__dmem1.varInsert(__Vfinal,"temp", &(TOP.top__DOT__dut__DOT__core__DOT__dmem1__DOT__temp), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,2 ,31,0 ,0,356);
        __Vscope_top__dut__core__imem1.varInsert(__Vfinal,"START_ADDR", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__imem1__DOT__START_ADDR))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__imem1.varInsert(__Vfinal,"address", &(TOP.top__DOT__dut__DOT__core__DOT__imem1__DOT__address), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__imem1.varInsert(__Vfinal,"address_2", &(TOP.top__DOT__dut__DOT__core__DOT__imem1__DOT__address_2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__imem1.varInsert(__Vfinal,"clock", &(TOP.top__DOT__dut__DOT__core__DOT__imem1__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__imem1.varInsert(__Vfinal,"data_in", &(TOP.top__DOT__dut__DOT__core__DOT__imem1__DOT__data_in), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__imem1.varInsert(__Vfinal,"data_in_2", &(TOP.top__DOT__dut__DOT__core__DOT__imem1__DOT__data_in_2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__imem1.varInsert(__Vfinal,"data_out", &(TOP.top__DOT__dut__DOT__core__DOT__imem1__DOT__data_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__imem1.varInsert(__Vfinal,"ea", &(TOP.top__DOT__dut__DOT__core__DOT__imem1__DOT__ea), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__imem1.varInsert(__Vfinal,"enable", &(TOP.top__DOT__dut__DOT__core__DOT__imem1__DOT__enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__imem1.varInsert(__Vfinal,"mem", &(TOP.top__DOT__dut__DOT__core__DOT__imem1__DOT__mem), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,2 ,31,0 ,0,262143);
        __Vscope_top__dut__core__imem1.varInsert(__Vfinal,"read_write", &(TOP.top__DOT__dut__DOT__core__DOT__imem1__DOT__read_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__imem1.varInsert(__Vfinal,"read_write_2", &(TOP.top__DOT__dut__DOT__core__DOT__imem1__DOT__read_write_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"ADDRW", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__ADDRW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"BASE_ADDR", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__BASE_ADDR))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"DATAW", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__DATAW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"NUM_REGS", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__NUM_REGS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"addr_rd", &(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__addr_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"addr_rs1", &(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__addr_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"addr_rs2", &(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__addr_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"clock", &(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__clock), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"data_rd", &(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"data_rs1", &(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"data_rs1_r", &(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs1_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"data_rs2", &(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"data_rs2_r", &(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs2_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"i", &(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"regs", &(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__regs), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,2 ,31,0 ,0,31);
        __Vscope_top__dut__core__rf1.varInsert(__Vfinal,"write_enable", &(TOP.top__DOT__dut__DOT__core__DOT__rf1__DOT__write_enable), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_top__dut__core__wb1.varInsert(__Vfinal,"DATAW", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__wb1__DOT__DATAW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__wb1.varInsert(__Vfinal,"WB_ALU", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__wb1__DOT__WB_ALU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__wb1.varInsert(__Vfinal,"WB_MEM", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__wb1__DOT__WB_MEM))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__wb1.varInsert(__Vfinal,"WB_PC4", const_cast<void*>(static_cast<const void*>(&(TOP.top__DOT__dut__DOT__core__DOT__wb1__DOT__WB_PC4))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__dut__core__wb1.varInsert(__Vfinal,"alu", &(TOP.top__DOT__dut__DOT__core__DOT__wb1__DOT__alu), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__wb1.varInsert(__Vfinal,"mem", &(TOP.top__DOT__dut__DOT__core__DOT__wb1__DOT__mem), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__wb1.varInsert(__Vfinal,"pc4", &(TOP.top__DOT__dut__DOT__core__DOT__wb1__DOT__pc4), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__wb1.varInsert(__Vfinal,"wb_data", &(TOP.top__DOT__dut__DOT__core__DOT__wb1__DOT__wb_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_top__dut__core__wb1.varInsert(__Vfinal,"wb_sel", &(TOP.top__DOT__dut__DOT__core__DOT__wb1__DOT__wb_sel), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_top__genblk1.varInsert(__Vfinal,"__trace_fd", &(TOP.top__DOT__genblk1__DOT_____05Ftrace_fd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
    }
}
