// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    bufp->chgBit(oldp+0,(vlSelf->top__DOT__clock));
    bufp->chgBit(oldp+1,(vlSelf->top__DOT__reset));
    bufp->chgBit(oldp+2,(vlSelf->top__DOT__clkg__DOT__clk));
    bufp->chgBit(oldp+3,(vlSelf->top__DOT__clkg__DOT__rst));
    bufp->chgIData(oldp+4,(vlSelf->top__DOT__clkg__DOT__counter),32);
    bufp->chgBit(oldp+5,(vlSelf->top__DOT__dut__DOT__clock));
    bufp->chgBit(oldp+6,(vlSelf->top__DOT__dut__DOT__reset));
    bufp->chgBit(oldp+7,(vlSelf->top__DOT__dut__DOT__core__DOT__clock));
    bufp->chgBit(oldp+8,(vlSelf->top__DOT__dut__DOT__core__DOT__reset));
    bufp->chgBit(oldp+9,(vlSelf->top__DOT__dut__DOT__core__DOT__fetch_en));
    bufp->chgBit(oldp+10,(vlSelf->top__DOT__dut__DOT__core__DOT__fd_en));
    bufp->chgBit(oldp+11,(vlSelf->top__DOT__dut__DOT__core__DOT__dx_en));
    bufp->chgBit(oldp+12,(vlSelf->top__DOT__dut__DOT__core__DOT__xm_en));
    bufp->chgBit(oldp+13,(vlSelf->top__DOT__dut__DOT__core__DOT__mw_en));
    bufp->chgIData(oldp+14,(vlSelf->top__DOT__dut__DOT__core__DOT__pc_r),32);
    bufp->chgIData(oldp+15,(vlSelf->top__DOT__dut__DOT__core__DOT__instr_w),32);
    bufp->chgIData(oldp+16,(vlSelf->top__DOT__dut__DOT__core__DOT__imem_in_r),32);
    bufp->chgBit(oldp+17,(vlSelf->top__DOT__dut__DOT__core__DOT__imem_rw_w));
    bufp->chgCData(oldp+18,(vlSelf->top__DOT__dut__DOT__core__DOT__opcode_w),7);
    bufp->chgCData(oldp+19,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rd_w),5);
    bufp->chgCData(oldp+20,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rs1_w),5);
    bufp->chgCData(oldp+21,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rs2_w),5);
    bufp->chgCData(oldp+22,(vlSelf->top__DOT__dut__DOT__core__DOT__funct3_w),3);
    bufp->chgCData(oldp+23,(vlSelf->top__DOT__dut__DOT__core__DOT__funct7_w),7);
    bufp->chgIData(oldp+24,(vlSelf->top__DOT__dut__DOT__core__DOT__imm_w),32);
    bufp->chgCData(oldp+25,(vlSelf->top__DOT__dut__DOT__core__DOT__shamt_w),5);
    bufp->chgBit(oldp+26,(vlSelf->top__DOT__dut__DOT__core__DOT__is_u_type));
    bufp->chgBit(oldp+27,(vlSelf->top__DOT__dut__DOT__core__DOT__is_j_type));
    bufp->chgBit(oldp+28,(vlSelf->top__DOT__dut__DOT__core__DOT__is_i_type));
    bufp->chgBit(oldp+29,(vlSelf->top__DOT__dut__DOT__core__DOT__reg_wen));
    bufp->chgBit(oldp+30,(vlSelf->top__DOT__dut__DOT__core__DOT__pc_sel));
    bufp->chgBit(oldp+31,(vlSelf->top__DOT__dut__DOT__core__DOT__br_un));
    bufp->chgCData(oldp+32,(vlSelf->top__DOT__dut__DOT__core__DOT__a_sel),2);
    bufp->chgCData(oldp+33,(vlSelf->top__DOT__dut__DOT__core__DOT__b_sel),2);
    bufp->chgCData(oldp+34,(vlSelf->top__DOT__dut__DOT__core__DOT__branch_comp_data1_sel),2);
    bufp->chgCData(oldp+35,(vlSelf->top__DOT__dut__DOT__core__DOT__branch_comp_data2_sel),2);
    bufp->chgCData(oldp+36,(vlSelf->top__DOT__dut__DOT__core__DOT__alu_sel),4);
    bufp->chgCData(oldp+37,(vlSelf->top__DOT__dut__DOT__core__DOT__wb_sel),2);
    bufp->chgBit(oldp+38,(vlSelf->top__DOT__dut__DOT__core__DOT__br_eq));
    bufp->chgBit(oldp+39,(vlSelf->top__DOT__dut__DOT__core__DOT__br_lt));
    bufp->chgBit(oldp+40,(vlSelf->top__DOT__dut__DOT__core__DOT__br_taken));
    bufp->chgIData(oldp+41,(vlSelf->top__DOT__dut__DOT__core__DOT__data_rs1_w),32);
    bufp->chgIData(oldp+42,(vlSelf->top__DOT__dut__DOT__core__DOT__data_rs2_w),32);
    bufp->chgIData(oldp+43,(vlSelf->top__DOT__dut__DOT__core__DOT__alu_in1_w),32);
    bufp->chgIData(oldp+44,(vlSelf->top__DOT__dut__DOT__core__DOT__alu_in2_w),32);
    bufp->chgIData(oldp+45,(vlSelf->top__DOT__dut__DOT__core__DOT__alu_out_w),32);
    bufp->chgIData(oldp+46,(vlSelf->top__DOT__dut__DOT__core__DOT__data_mem_w),32);
    bufp->chgBit(oldp+47,(vlSelf->top__DOT__dut__DOT__core__DOT__data_mem_rw));
    bufp->chgIData(oldp+48,(vlSelf->top__DOT__dut__DOT__core__DOT__data_rd_w),32);
    bufp->chgIData(oldp+49,(vlSelf->top__DOT__dut__DOT__core__DOT__pc4_f_w),32);
    bufp->chgIData(oldp+50,(vlSelf->top__DOT__dut__DOT__core__DOT__pc_fd_r),32);
    bufp->chgIData(oldp+51,(vlSelf->top__DOT__dut__DOT__core__DOT__pc_dx_r),32);
    bufp->chgCData(oldp+52,(vlSelf->top__DOT__dut__DOT__core__DOT__opcode_dx_r),7);
    bufp->chgCData(oldp+53,(vlSelf->top__DOT__dut__DOT__core__DOT__funct3_dx_r),3);
    bufp->chgIData(oldp+54,(vlSelf->top__DOT__dut__DOT__core__DOT__imm_dx_r),32);
    bufp->chgCData(oldp+55,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rs1_dx_r),5);
    bufp->chgCData(oldp+56,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rs2_dx_r),5);
    bufp->chgCData(oldp+57,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rd_dx_r),5);
    bufp->chgCData(oldp+58,(vlSelf->top__DOT__dut__DOT__core__DOT__funct7_dx_r),7);
    bufp->chgIData(oldp+59,(vlSelf->top__DOT__dut__DOT__core__DOT__pc_xm_r),32);
    bufp->chgIData(oldp+60,(vlSelf->top__DOT__dut__DOT__core__DOT__imm_xm_r),32);
    bufp->chgCData(oldp+61,(vlSelf->top__DOT__dut__DOT__core__DOT__funct3_xm_r),3);
    bufp->chgIData(oldp+62,(vlSelf->top__DOT__dut__DOT__core__DOT__alu_xm_r),32);
    bufp->chgIData(oldp+63,(vlSelf->top__DOT__dut__DOT__core__DOT__data_rs2_xm_r),32);
    bufp->chgCData(oldp+64,(vlSelf->top__DOT__dut__DOT__core__DOT__opcode_xm_r),7);
    bufp->chgCData(oldp+65,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rs2_xm_r),5);
    bufp->chgCData(oldp+66,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rd_xm_r),5);
    bufp->chgIData(oldp+67,(vlSelf->top__DOT__dut__DOT__core__DOT__pc_mw_r),32);
    bufp->chgCData(oldp+68,(vlSelf->top__DOT__dut__DOT__core__DOT__opcode_mw_r),7);
    bufp->chgCData(oldp+69,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rd_mw_r),5);
    bufp->chgBit(oldp+70,(vlSelf->top__DOT__dut__DOT__core__DOT__is_load_dx));
    bufp->chgBit(oldp+71,(vlSelf->top__DOT__dut__DOT__core__DOT__is_store_fd));
    bufp->chgBit(oldp+72,(vlSelf->top__DOT__dut__DOT__core__DOT__is_load_xm));
    bufp->chgBit(oldp+73,(vlSelf->top__DOT__dut__DOT__core__DOT__is_nop_mw));
    bufp->chgBit(oldp+74,(vlSelf->top__DOT__dut__DOT__core__DOT__is_nop_xm));
    bufp->chgBit(oldp+75,(vlSelf->top__DOT__dut__DOT__core__DOT__load_stall));
    bufp->chgBit(oldp+76,(vlSelf->top__DOT__dut__DOT__core__DOT__instr_mw_writes_reg));
    bufp->chgBit(oldp+77,(vlSelf->top__DOT__dut__DOT__core__DOT__wd_stall));
    bufp->chgBit(oldp+78,(vlSelf->top__DOT__dut__DOT__core__DOT__load_store_stall));
    bufp->chgBit(oldp+79,(vlSelf->top__DOT__dut__DOT__core__DOT__instr_xm_writes_reg));
    bufp->chgBit(oldp+80,(vlSelf->top__DOT__dut__DOT__core__DOT__store_rs2_stall));
    bufp->chgBit(oldp+81,(vlSelf->top__DOT__dut__DOT__core__DOT__stall));
    bufp->chgBit(oldp+82,(vlSelf->top__DOT__dut__DOT__core__DOT__imem_enable));
    bufp->chgBit(oldp+83,(vlSelf->top__DOT__dut__DOT__core__DOT__stall_fd));
    bufp->chgIData(oldp+84,(vlSelf->top__DOT__dut__DOT__core__DOT__prev_instr),32);
    bufp->chgIData(oldp+85,(vlSelf->top__DOT__dut__DOT__core__DOT__instr_fd_w),32);
    bufp->chgIData(oldp+86,(vlSelf->top__DOT__dut__DOT__core__DOT__pc4_xm_w),32);
    bufp->chgIData(oldp+87,(vlSelf->top__DOT__dut__DOT__core__DOT__pc4_mw_r),32);
    bufp->chgIData(oldp+88,(vlSelf->top__DOT__dut__DOT__core__DOT__alu_mw_r),32);
    bufp->chgCData(oldp+89,(vlSelf->top__DOT__dut__DOT__core__DOT__funct3_mw_r),3);
    bufp->chgIData(oldp+90,(vlSelf->top__DOT__dut__DOT__core__DOT__data_rs1_stall_w),32);
    bufp->chgIData(oldp+91,(vlSelf->top__DOT__dut__DOT__core__DOT__data_rs2_stall_w),32);
    bufp->chgIData(oldp+92,(vlSelf->top__DOT__dut__DOT__core__DOT__idata1_in),32);
    bufp->chgIData(oldp+93,(vlSelf->top__DOT__dut__DOT__core__DOT__idata2_in),32);
    bufp->chgCData(oldp+94,(vlSelf->top__DOT__dut__DOT__core__DOT__mem_write_access_size),2);
    bufp->chgBit(oldp+95,(vlSelf->top__DOT__dut__DOT__core__DOT__is_store_xm));
    bufp->chgBit(oldp+96,(vlSelf->top__DOT__dut__DOT__core__DOT__wm_forward));
    bufp->chgIData(oldp+97,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem_data_in),32);
    bufp->chgCData(oldp+98,(vlSelf->top__DOT__dut__DOT__core__DOT__mem_read_access_size),2);
    bufp->chgBit(oldp+99,(vlSelf->top__DOT__dut__DOT__core__DOT__is_unsigned));
    bufp->chgIData(oldp+100,(vlSelf->top__DOT__dut__DOT__core__DOT__data_mem_w_sized),32);
    bufp->chgIData(oldp+101,(vlSelf->top__DOT__dut__DOT__core__DOT__al1__DOT__idata1),32);
    bufp->chgIData(oldp+102,(vlSelf->top__DOT__dut__DOT__core__DOT__al1__DOT__idata2),32);
    bufp->chgCData(oldp+103,(vlSelf->top__DOT__dut__DOT__core__DOT__al1__DOT__alu_sel),4);
    bufp->chgIData(oldp+104,(vlSelf->top__DOT__dut__DOT__core__DOT__al1__DOT__odata),32);
    bufp->chgIData(oldp+105,(vlSelf->top__DOT__dut__DOT__core__DOT__al1__DOT__mask),32);
    bufp->chgIData(oldp+106,(vlSelf->top__DOT__dut__DOT__core__DOT__bc1__DOT__idata1),32);
    bufp->chgIData(oldp+107,(vlSelf->top__DOT__dut__DOT__core__DOT__bc1__DOT__idata2),32);
    bufp->chgBit(oldp+108,(vlSelf->top__DOT__dut__DOT__core__DOT__bc1__DOT__br_un));
    bufp->chgBit(oldp+109,(vlSelf->top__DOT__dut__DOT__core__DOT__bc1__DOT__br_eq));
    bufp->chgBit(oldp+110,(vlSelf->top__DOT__dut__DOT__core__DOT__bc1__DOT__br_lt));
    bufp->chgBit(oldp+111,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__clock));
    bufp->chgBit(oldp+112,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__reset));
    bufp->chgBit(oldp+113,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__dx_en));
    bufp->chgBit(oldp+114,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__xm_en));
    bufp->chgBit(oldp+115,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__mw_en));
    bufp->chgCData(oldp+116,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__opcode_dx),7);
    bufp->chgCData(oldp+117,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__opcode_xm),7);
    bufp->chgCData(oldp+118,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__opcode_mw),7);
    bufp->chgCData(oldp+119,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__funct3),3);
    bufp->chgCData(oldp+120,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__funct7),7);
    bufp->chgBit(oldp+121,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__br_eq));
    bufp->chgBit(oldp+122,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__br_lt));
    bufp->chgCData(oldp+123,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rs1_dx),5);
    bufp->chgCData(oldp+124,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rs2_dx),5);
    bufp->chgCData(oldp+125,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rd_xm),5);
    bufp->chgCData(oldp+126,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rd_mw),5);
    bufp->chgCData(oldp+127,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__branch_comp_data1_sel),2);
    bufp->chgCData(oldp+128,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__branch_comp_data2_sel),2);
    bufp->chgBit(oldp+129,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__br_taken));
    bufp->chgBit(oldp+130,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__pc_sel));
    bufp->chgBit(oldp+131,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__br_un));
    bufp->chgCData(oldp+132,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__a_sel),2);
    bufp->chgCData(oldp+133,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__b_sel),2);
    bufp->chgCData(oldp+134,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__alu_sel),4);
    bufp->chgBit(oldp+135,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__mem_rw));
    bufp->chgBit(oldp+136,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__reg_wen));
    bufp->chgCData(oldp+137,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__wb_sel),2);
    bufp->chgBit(oldp+138,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_branch_x));
    bufp->chgBit(oldp+139,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_alu_x));
    bufp->chgBit(oldp+140,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_alu_imm_x));
    bufp->chgBit(oldp+141,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jal_x));
    bufp->chgBit(oldp+142,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_auipc_x));
    bufp->chgBit(oldp+143,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_lui_x));
    bufp->chgBit(oldp+144,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_load_x));
    bufp->chgBit(oldp+145,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_store_x));
    bufp->chgBit(oldp+146,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jalr_x));
    bufp->chgBit(oldp+147,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_x));
    bufp->chgBit(oldp+148,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_u_type_x));
    bufp->chgBit(oldp+149,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__branch_taken));
    bufp->chgBit(oldp+150,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_store_xm_r));
    bufp->chgBit(oldp+151,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_load_xm_r));
    bufp->chgBit(oldp+152,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jal_xm_r));
    bufp->chgBit(oldp+153,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jalr_xm_r));
    bufp->chgBit(oldp+154,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_branch_xm_r));
    bufp->chgBit(oldp+155,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_xm_r));
    bufp->chgBit(oldp+156,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_store_mw_r));
    bufp->chgBit(oldp+157,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_branch_mw_r));
    bufp->chgBit(oldp+158,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_mw_r));
    bufp->chgBit(oldp+159,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_load_mw_r));
    bufp->chgBit(oldp+160,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jal_mw_r));
    bufp->chgBit(oldp+161,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jalr_mw_r));
    bufp->chgBit(oldp+162,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__insn_xm_writes_reg));
    bufp->chgBit(oldp+163,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__insn_mw_writes_reg));
    bufp->chgBit(oldp+164,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_wb));
    bufp->chgBit(oldp+165,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_nop));
    bufp->chgIData(oldp+166,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__instr),32);
    bufp->chgCData(oldp+167,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__opcode),7);
    bufp->chgCData(oldp+168,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__addr_rd),5);
    bufp->chgCData(oldp+169,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__addr_rs1),5);
    bufp->chgCData(oldp+170,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__addr_rs2),5);
    bufp->chgCData(oldp+171,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__funct3),3);
    bufp->chgCData(oldp+172,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__funct7),7);
    bufp->chgIData(oldp+173,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__imm),32);
    bufp->chgCData(oldp+174,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__shamt),5);
    bufp->chgBit(oldp+175,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_u_type_w));
    bufp->chgBit(oldp+176,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_j_type_w));
    bufp->chgBit(oldp+177,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_i_type_w));
    bufp->chgBit(oldp+178,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_i_shift));
    bufp->chgBit(oldp+179,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_alu));
    bufp->chgBit(oldp+180,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_alu_imm));
    bufp->chgBit(oldp+181,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_load));
    bufp->chgBit(oldp+182,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_store));
    bufp->chgBit(oldp+183,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_branch));
    bufp->chgBit(oldp+184,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_jal));
    bufp->chgBit(oldp+185,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_jalr));
    bufp->chgBit(oldp+186,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_lui));
    bufp->chgBit(oldp+187,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_auipc));
    bufp->chgBit(oldp+188,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_ecall));
    bufp->chgBit(oldp+189,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_r_type));
    bufp->chgBit(oldp+190,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_i_type));
    bufp->chgBit(oldp+191,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_s_type));
    bufp->chgBit(oldp+192,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_b_type));
    bufp->chgBit(oldp+193,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_u_type));
    bufp->chgBit(oldp+194,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_j_type));
    bufp->chgBit(oldp+195,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__clock));
    bufp->chgBit(oldp+196,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__read_write));
    bufp->chgCData(oldp+197,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__access_size),2);
    bufp->chgIData(oldp+198,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__address),32);
    bufp->chgIData(oldp+199,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__data_in),32);
    bufp->chgIData(oldp+200,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__data_out),32);
    bufp->chgIData(oldp+201,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__addr),32);
    bufp->chgIData(oldp+202,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__i),32);
    bufp->chgBit(oldp+203,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__clock));
    bufp->chgIData(oldp+204,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__address),32);
    bufp->chgIData(oldp+205,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__data_in),32);
    bufp->chgBit(oldp+206,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__read_write));
    bufp->chgBit(oldp+207,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__enable));
    bufp->chgIData(oldp+208,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__data_out),32);
    bufp->chgIData(oldp+209,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__address_2),32);
    bufp->chgIData(oldp+210,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__ea),32);
    bufp->chgIData(oldp+211,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__data_in_2),32);
    bufp->chgBit(oldp+212,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__read_write_2));
    bufp->chgBit(oldp+213,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__clock));
    bufp->chgBit(oldp+214,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__write_enable));
    bufp->chgCData(oldp+215,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__addr_rs1),5);
    bufp->chgCData(oldp+216,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__addr_rs2),5);
    bufp->chgCData(oldp+217,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__addr_rd),5);
    bufp->chgIData(oldp+218,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rd),32);
    bufp->chgIData(oldp+219,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs1),32);
    bufp->chgIData(oldp+220,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs2),32);
    bufp->chgIData(oldp+221,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[0]),32);
    bufp->chgIData(oldp+222,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[1]),32);
    bufp->chgIData(oldp+223,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[2]),32);
    bufp->chgIData(oldp+224,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[3]),32);
    bufp->chgIData(oldp+225,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[4]),32);
    bufp->chgIData(oldp+226,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[5]),32);
    bufp->chgIData(oldp+227,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[6]),32);
    bufp->chgIData(oldp+228,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[7]),32);
    bufp->chgIData(oldp+229,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[8]),32);
    bufp->chgIData(oldp+230,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[9]),32);
    bufp->chgIData(oldp+231,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[10]),32);
    bufp->chgIData(oldp+232,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[11]),32);
    bufp->chgIData(oldp+233,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[12]),32);
    bufp->chgIData(oldp+234,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[13]),32);
    bufp->chgIData(oldp+235,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[14]),32);
    bufp->chgIData(oldp+236,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[15]),32);
    bufp->chgIData(oldp+237,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[16]),32);
    bufp->chgIData(oldp+238,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[17]),32);
    bufp->chgIData(oldp+239,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[18]),32);
    bufp->chgIData(oldp+240,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[19]),32);
    bufp->chgIData(oldp+241,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[20]),32);
    bufp->chgIData(oldp+242,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[21]),32);
    bufp->chgIData(oldp+243,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[22]),32);
    bufp->chgIData(oldp+244,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[23]),32);
    bufp->chgIData(oldp+245,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[24]),32);
    bufp->chgIData(oldp+246,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[25]),32);
    bufp->chgIData(oldp+247,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[26]),32);
    bufp->chgIData(oldp+248,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[27]),32);
    bufp->chgIData(oldp+249,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[28]),32);
    bufp->chgIData(oldp+250,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[29]),32);
    bufp->chgIData(oldp+251,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[30]),32);
    bufp->chgIData(oldp+252,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[31]),32);
    bufp->chgIData(oldp+253,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs1_r),32);
    bufp->chgIData(oldp+254,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs2_r),32);
    bufp->chgIData(oldp+255,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__i),32);
    bufp->chgIData(oldp+256,(vlSelf->top__DOT__dut__DOT__core__DOT__wb1__DOT__alu),32);
    bufp->chgIData(oldp+257,(vlSelf->top__DOT__dut__DOT__core__DOT__wb1__DOT__pc4),32);
    bufp->chgIData(oldp+258,(vlSelf->top__DOT__dut__DOT__core__DOT__wb1__DOT__mem),32);
    bufp->chgCData(oldp+259,(vlSelf->top__DOT__dut__DOT__core__DOT__wb1__DOT__wb_sel),2);
    bufp->chgIData(oldp+260,(vlSelf->top__DOT__dut__DOT__core__DOT__wb1__DOT__wb_data),32);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
