// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushPrefix("top", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+1,0,"clock",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("clkg", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+3,0,"clk",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+4,0,"rst",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+5,0,"counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("dut", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+6,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+7,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("core", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+262,0,"DATAW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+263,0,"BASE_ADDR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+264,0,"ADDRW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+264,0,"N_BITS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+8,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+9,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+10,0,"fetch_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+11,0,"fd_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+12,0,"dx_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+13,0,"xm_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+14,0,"mw_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+15,0,"pc_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+16,0,"instr_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+17,0,"imem_in_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+18,0,"imem_rw_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"opcode_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+20,0,"addr_rd_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+21,0,"addr_rs1_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+22,0,"addr_rs2_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+23,0,"funct3_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+24,0,"funct7_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+25,0,"imm_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+26,0,"shamt_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+27,0,"is_u_type",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+28,0,"is_j_type",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+29,0,"is_i_type",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+30,0,"reg_wen",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+31,0,"pc_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+32,0,"br_un",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+33,0,"a_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+34,0,"b_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+35,0,"branch_comp_data1_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+36,0,"branch_comp_data2_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+37,0,"alu_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+38,0,"wb_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+39,0,"br_eq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+40,0,"br_lt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+41,0,"br_taken",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+42,0,"data_rs1_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+43,0,"data_rs2_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+44,0,"alu_in1_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+45,0,"alu_in2_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+46,0,"alu_out_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+47,0,"data_mem_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+48,0,"data_mem_rw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+49,0,"data_rd_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+50,0,"pc4_f_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+51,0,"pc_fd_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+52,0,"pc_dx_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+53,0,"opcode_dx_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+54,0,"funct3_dx_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+55,0,"imm_dx_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+56,0,"addr_rs1_dx_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+57,0,"addr_rs2_dx_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+58,0,"addr_rd_dx_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+59,0,"funct7_dx_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+60,0,"pc_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+61,0,"imm_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+62,0,"funct3_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+63,0,"alu_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+64,0,"data_rs2_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+65,0,"opcode_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+66,0,"addr_rs2_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+67,0,"addr_rd_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+68,0,"pc_mw_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+69,0,"opcode_mw_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+70,0,"addr_rd_mw_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+265,0,"NOP_INSTR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+266,0,"NOP_OPCODE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+267,0,"LOAD_OPCODE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+268,0,"STORE_OPCODE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+269,0,"BRANCH_OPCODE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+270,0,"ECALL_OPCODE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+71,0,"is_load_dx",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+72,0,"is_store_fd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+73,0,"is_load_xm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+74,0,"is_nop_mw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+75,0,"is_nop_xm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+76,0,"load_stall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+77,0,"instr_mw_writes_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+78,0,"wd_stall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+79,0,"load_store_stall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+80,0,"instr_xm_writes_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+81,0,"store_rs2_stall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+82,0,"stall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+83,0,"imem_enable",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+84,0,"stall_fd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+85,0,"prev_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+86,0,"instr_fd_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+87,0,"pc4_xm_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+88,0,"pc4_mw_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+89,0,"alu_mw_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+90,0,"funct3_mw_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+91,0,"data_rs1_stall_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+92,0,"data_rs2_stall_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+271,0,"REG",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+272,0,"PC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+273,0,"WX_BYPASS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+274,0,"MX_BYPASS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+93,0,"idata1_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+94,0,"idata2_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+272,0,"IMM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+95,0,"mem_write_access_size",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+96,0,"is_store_xm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+97,0,"wm_forward",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+98,0,"dmem_data_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+99,0,"mem_read_access_size",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+271,0,"BYTE_OP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+272,0,"HALF_OP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+273,0,"WORD_OP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+100,0,"is_unsigned",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+101,0,"data_mem_w_sized",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("al1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+262,0,"IDATAW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+262,0,"ODATAW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+102,0,"idata1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+103,0,"idata2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+104,0,"alu_sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+105,0,"odata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+275,0,"ADD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+276,0,"SUB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+277,0,"SLL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+278,0,"SRL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+279,0,"SRA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+280,0,"SLT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+281,0,"SLTU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+282,0,"XOR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+283,0,"OR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+284,0,"AND",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+285,0,"NOP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+286,0,"MUL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+287,0,"DIV",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+288,0,"DIVU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+106,0,"mask",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("bc1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+262,0,"IDATAW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+107,0,"idata1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+108,0,"idata2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+109,0,"br_un",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+110,0,"br_eq",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+111,0,"br_lt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("cs1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+262,0,"DATAW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+264,0,"ADDRW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+112,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+113,0,"reset",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+114,0,"dx_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+115,0,"xm_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+116,0,"mw_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+117,0,"opcode_dx",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+118,0,"opcode_xm",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+119,0,"opcode_mw",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+120,0,"funct3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+121,0,"funct7",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBit(c+122,0,"br_eq",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+123,0,"br_lt",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+124,0,"addr_rs1_dx",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+125,0,"addr_rs2_dx",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+126,0,"addr_rd_xm",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+127,0,"addr_rd_mw",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+128,0,"branch_comp_data1_sel",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+129,0,"branch_comp_data2_sel",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+130,0,"br_taken",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"pc_sel",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+132,0,"br_un",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+133,0,"a_sel",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+134,0,"b_sel",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+135,0,"alu_sel",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+136,0,"mem_rw",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"reg_wen",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+138,0,"wb_sel",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+275,0,"ADD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+276,0,"SUB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+277,0,"SLL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+278,0,"SRL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+279,0,"SRA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+280,0,"SLT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+281,0,"SLTU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+282,0,"XOR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+283,0,"OR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+284,0,"AND",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+285,0,"NOP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+286,0,"MUL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+287,0,"DIV",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+288,0,"DIVU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+271,0,"WB_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+272,0,"WB_ALU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+273,0,"WB_PC4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+139,0,"is_branch_x",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+140,0,"is_alu_x",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+141,0,"is_alu_imm_x",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+142,0,"is_jal_x",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+143,0,"is_auipc_x",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+144,0,"is_lui_x",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+145,0,"is_load_x",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+146,0,"is_store_x",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+147,0,"is_jalr_x",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+148,0,"is_ecall_x",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+149,0,"is_u_type_x",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+150,0,"branch_taken",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+271,0,"REG",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+272,0,"PC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+273,0,"WX_BYPASS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+274,0,"MX_BYPASS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+272,0,"IMM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+151,0,"is_store_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+152,0,"is_load_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+153,0,"is_jal_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+154,0,"is_jalr_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+155,0,"is_branch_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+156,0,"is_ecall_xm_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+157,0,"is_store_mw_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+158,0,"is_branch_mw_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+159,0,"is_ecall_mw_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+160,0,"is_load_mw_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+161,0,"is_jal_mw_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+162,0,"is_jalr_mw_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+163,0,"insn_xm_writes_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+164,0,"insn_mw_writes_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+165,0,"is_ecall_wb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+166,0,"is_nop",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("dec1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+262,0,"DATAW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+264,0,"ADDRW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+264,0,"N_BITS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+167,0,"instr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+168,0,"opcode",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+169,0,"addr_rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+170,0,"addr_rs1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+171,0,"addr_rs2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+172,0,"funct3",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+173,0,"funct7",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+174,0,"imm",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+175,0,"shamt",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+176,0,"is_u_type_w",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+177,0,"is_j_type_w",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+178,0,"is_i_type_w",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+289,0,"IMM_SIZE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+290,0,"IMM_UJ_SIZE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+179,0,"is_i_shift",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+180,0,"is_alu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+181,0,"is_alu_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+182,0,"is_load",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+183,0,"is_store",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+184,0,"is_branch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+185,0,"is_jal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+186,0,"is_jalr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+187,0,"is_lui",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+188,0,"is_auipc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+189,0,"is_ecall",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+190,0,"is_r_type",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+191,0,"is_i_type",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+192,0,"is_s_type",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+193,0,"is_b_type",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+194,0,"is_u_type",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+195,0,"is_j_type",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("dmem1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+291,0,"BASE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+196,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+197,0,"read_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+198,0,"access_size",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+199,0,"address",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+200,0,"data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+201,0,"data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+202,0,"addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+203,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("imem1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+204,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+205,0,"address",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+206,0,"data_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+207,0,"read_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+208,0,"enable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+209,0,"data_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+210,0,"address_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+211,0,"ea",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+212,0,"data_in_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+213,0,"read_write_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+263,0,"START_ADDR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("rf1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+262,0,"DATAW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+264,0,"ADDRW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+262,0,"NUM_REGS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+263,0,"BASE_ADDR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+214,0,"clock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+215,0,"write_enable",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+216,0,"addr_rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+217,0,"addr_rs2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+218,0,"addr_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+219,0,"data_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+220,0,"data_rs1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+221,0,"data_rs2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("regs", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+222+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+254,0,"data_rs1_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+255,0,"data_rs2_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+256,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("wb1", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+262,0,"DATAW",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+257,0,"alu",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+258,0,"pc4",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+259,0,"mem",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+260,0,"wb_sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+261,0,"wb_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+271,0,"WB_MEM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+272,0,"WB_ALU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+273,0,"WB_PC4",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+262,(0x20U),32);
    bufp->fullIData(oldp+263,(0x1000000U),32);
    bufp->fullIData(oldp+264,(5U),32);
    bufp->fullIData(oldp+265,(0x13U),32);
    bufp->fullCData(oldp+266,(0x13U),7);
    bufp->fullCData(oldp+267,(3U),7);
    bufp->fullCData(oldp+268,(0x23U),7);
    bufp->fullCData(oldp+269,(0x63U),7);
    bufp->fullCData(oldp+270,(0x73U),7);
    bufp->fullCData(oldp+271,(0U),2);
    bufp->fullCData(oldp+272,(1U),2);
    bufp->fullCData(oldp+273,(2U),2);
    bufp->fullCData(oldp+274,(3U),2);
    bufp->fullCData(oldp+275,(0U),4);
    bufp->fullCData(oldp+276,(1U),4);
    bufp->fullCData(oldp+277,(2U),4);
    bufp->fullCData(oldp+278,(3U),4);
    bufp->fullCData(oldp+279,(4U),4);
    bufp->fullCData(oldp+280,(5U),4);
    bufp->fullCData(oldp+281,(6U),4);
    bufp->fullCData(oldp+282,(7U),4);
    bufp->fullCData(oldp+283,(8U),4);
    bufp->fullCData(oldp+284,(9U),4);
    bufp->fullCData(oldp+285,(0xaU),4);
    bufp->fullCData(oldp+286,(0xbU),4);
    bufp->fullCData(oldp+287,(0xcU),4);
    bufp->fullCData(oldp+288,(0xdU),4);
    bufp->fullIData(oldp+289,(0xcU),32);
    bufp->fullIData(oldp+290,(0x14U),32);
    bufp->fullIData(oldp+291,(0x1000000U),32);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelf->top__DOT__clock));
    bufp->fullBit(oldp+2,(vlSelf->top__DOT__reset));
    bufp->fullBit(oldp+3,(vlSelf->top__DOT__clkg__DOT__clk));
    bufp->fullBit(oldp+4,(vlSelf->top__DOT__clkg__DOT__rst));
    bufp->fullIData(oldp+5,(vlSelf->top__DOT__clkg__DOT__counter),32);
    bufp->fullBit(oldp+6,(vlSelf->top__DOT__dut__DOT__clock));
    bufp->fullBit(oldp+7,(vlSelf->top__DOT__dut__DOT__reset));
    bufp->fullBit(oldp+8,(vlSelf->top__DOT__dut__DOT__core__DOT__clock));
    bufp->fullBit(oldp+9,(vlSelf->top__DOT__dut__DOT__core__DOT__reset));
    bufp->fullBit(oldp+10,(vlSelf->top__DOT__dut__DOT__core__DOT__fetch_en));
    bufp->fullBit(oldp+11,(vlSelf->top__DOT__dut__DOT__core__DOT__fd_en));
    bufp->fullBit(oldp+12,(vlSelf->top__DOT__dut__DOT__core__DOT__dx_en));
    bufp->fullBit(oldp+13,(vlSelf->top__DOT__dut__DOT__core__DOT__xm_en));
    bufp->fullBit(oldp+14,(vlSelf->top__DOT__dut__DOT__core__DOT__mw_en));
    bufp->fullIData(oldp+15,(vlSelf->top__DOT__dut__DOT__core__DOT__pc_r),32);
    bufp->fullIData(oldp+16,(vlSelf->top__DOT__dut__DOT__core__DOT__instr_w),32);
    bufp->fullIData(oldp+17,(vlSelf->top__DOT__dut__DOT__core__DOT__imem_in_r),32);
    bufp->fullBit(oldp+18,(vlSelf->top__DOT__dut__DOT__core__DOT__imem_rw_w));
    bufp->fullCData(oldp+19,(vlSelf->top__DOT__dut__DOT__core__DOT__opcode_w),7);
    bufp->fullCData(oldp+20,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rd_w),5);
    bufp->fullCData(oldp+21,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rs1_w),5);
    bufp->fullCData(oldp+22,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rs2_w),5);
    bufp->fullCData(oldp+23,(vlSelf->top__DOT__dut__DOT__core__DOT__funct3_w),3);
    bufp->fullCData(oldp+24,(vlSelf->top__DOT__dut__DOT__core__DOT__funct7_w),7);
    bufp->fullIData(oldp+25,(vlSelf->top__DOT__dut__DOT__core__DOT__imm_w),32);
    bufp->fullCData(oldp+26,(vlSelf->top__DOT__dut__DOT__core__DOT__shamt_w),5);
    bufp->fullBit(oldp+27,(vlSelf->top__DOT__dut__DOT__core__DOT__is_u_type));
    bufp->fullBit(oldp+28,(vlSelf->top__DOT__dut__DOT__core__DOT__is_j_type));
    bufp->fullBit(oldp+29,(vlSelf->top__DOT__dut__DOT__core__DOT__is_i_type));
    bufp->fullBit(oldp+30,(vlSelf->top__DOT__dut__DOT__core__DOT__reg_wen));
    bufp->fullBit(oldp+31,(vlSelf->top__DOT__dut__DOT__core__DOT__pc_sel));
    bufp->fullBit(oldp+32,(vlSelf->top__DOT__dut__DOT__core__DOT__br_un));
    bufp->fullCData(oldp+33,(vlSelf->top__DOT__dut__DOT__core__DOT__a_sel),2);
    bufp->fullCData(oldp+34,(vlSelf->top__DOT__dut__DOT__core__DOT__b_sel),2);
    bufp->fullCData(oldp+35,(vlSelf->top__DOT__dut__DOT__core__DOT__branch_comp_data1_sel),2);
    bufp->fullCData(oldp+36,(vlSelf->top__DOT__dut__DOT__core__DOT__branch_comp_data2_sel),2);
    bufp->fullCData(oldp+37,(vlSelf->top__DOT__dut__DOT__core__DOT__alu_sel),4);
    bufp->fullCData(oldp+38,(vlSelf->top__DOT__dut__DOT__core__DOT__wb_sel),2);
    bufp->fullBit(oldp+39,(vlSelf->top__DOT__dut__DOT__core__DOT__br_eq));
    bufp->fullBit(oldp+40,(vlSelf->top__DOT__dut__DOT__core__DOT__br_lt));
    bufp->fullBit(oldp+41,(vlSelf->top__DOT__dut__DOT__core__DOT__br_taken));
    bufp->fullIData(oldp+42,(vlSelf->top__DOT__dut__DOT__core__DOT__data_rs1_w),32);
    bufp->fullIData(oldp+43,(vlSelf->top__DOT__dut__DOT__core__DOT__data_rs2_w),32);
    bufp->fullIData(oldp+44,(vlSelf->top__DOT__dut__DOT__core__DOT__alu_in1_w),32);
    bufp->fullIData(oldp+45,(vlSelf->top__DOT__dut__DOT__core__DOT__alu_in2_w),32);
    bufp->fullIData(oldp+46,(vlSelf->top__DOT__dut__DOT__core__DOT__alu_out_w),32);
    bufp->fullIData(oldp+47,(vlSelf->top__DOT__dut__DOT__core__DOT__data_mem_w),32);
    bufp->fullBit(oldp+48,(vlSelf->top__DOT__dut__DOT__core__DOT__data_mem_rw));
    bufp->fullIData(oldp+49,(vlSelf->top__DOT__dut__DOT__core__DOT__data_rd_w),32);
    bufp->fullIData(oldp+50,(vlSelf->top__DOT__dut__DOT__core__DOT__pc4_f_w),32);
    bufp->fullIData(oldp+51,(vlSelf->top__DOT__dut__DOT__core__DOT__pc_fd_r),32);
    bufp->fullIData(oldp+52,(vlSelf->top__DOT__dut__DOT__core__DOT__pc_dx_r),32);
    bufp->fullCData(oldp+53,(vlSelf->top__DOT__dut__DOT__core__DOT__opcode_dx_r),7);
    bufp->fullCData(oldp+54,(vlSelf->top__DOT__dut__DOT__core__DOT__funct3_dx_r),3);
    bufp->fullIData(oldp+55,(vlSelf->top__DOT__dut__DOT__core__DOT__imm_dx_r),32);
    bufp->fullCData(oldp+56,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rs1_dx_r),5);
    bufp->fullCData(oldp+57,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rs2_dx_r),5);
    bufp->fullCData(oldp+58,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rd_dx_r),5);
    bufp->fullCData(oldp+59,(vlSelf->top__DOT__dut__DOT__core__DOT__funct7_dx_r),7);
    bufp->fullIData(oldp+60,(vlSelf->top__DOT__dut__DOT__core__DOT__pc_xm_r),32);
    bufp->fullIData(oldp+61,(vlSelf->top__DOT__dut__DOT__core__DOT__imm_xm_r),32);
    bufp->fullCData(oldp+62,(vlSelf->top__DOT__dut__DOT__core__DOT__funct3_xm_r),3);
    bufp->fullIData(oldp+63,(vlSelf->top__DOT__dut__DOT__core__DOT__alu_xm_r),32);
    bufp->fullIData(oldp+64,(vlSelf->top__DOT__dut__DOT__core__DOT__data_rs2_xm_r),32);
    bufp->fullCData(oldp+65,(vlSelf->top__DOT__dut__DOT__core__DOT__opcode_xm_r),7);
    bufp->fullCData(oldp+66,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rs2_xm_r),5);
    bufp->fullCData(oldp+67,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rd_xm_r),5);
    bufp->fullIData(oldp+68,(vlSelf->top__DOT__dut__DOT__core__DOT__pc_mw_r),32);
    bufp->fullCData(oldp+69,(vlSelf->top__DOT__dut__DOT__core__DOT__opcode_mw_r),7);
    bufp->fullCData(oldp+70,(vlSelf->top__DOT__dut__DOT__core__DOT__addr_rd_mw_r),5);
    bufp->fullBit(oldp+71,(vlSelf->top__DOT__dut__DOT__core__DOT__is_load_dx));
    bufp->fullBit(oldp+72,(vlSelf->top__DOT__dut__DOT__core__DOT__is_store_fd));
    bufp->fullBit(oldp+73,(vlSelf->top__DOT__dut__DOT__core__DOT__is_load_xm));
    bufp->fullBit(oldp+74,(vlSelf->top__DOT__dut__DOT__core__DOT__is_nop_mw));
    bufp->fullBit(oldp+75,(vlSelf->top__DOT__dut__DOT__core__DOT__is_nop_xm));
    bufp->fullBit(oldp+76,(vlSelf->top__DOT__dut__DOT__core__DOT__load_stall));
    bufp->fullBit(oldp+77,(vlSelf->top__DOT__dut__DOT__core__DOT__instr_mw_writes_reg));
    bufp->fullBit(oldp+78,(vlSelf->top__DOT__dut__DOT__core__DOT__wd_stall));
    bufp->fullBit(oldp+79,(vlSelf->top__DOT__dut__DOT__core__DOT__load_store_stall));
    bufp->fullBit(oldp+80,(vlSelf->top__DOT__dut__DOT__core__DOT__instr_xm_writes_reg));
    bufp->fullBit(oldp+81,(vlSelf->top__DOT__dut__DOT__core__DOT__store_rs2_stall));
    bufp->fullBit(oldp+82,(vlSelf->top__DOT__dut__DOT__core__DOT__stall));
    bufp->fullBit(oldp+83,(vlSelf->top__DOT__dut__DOT__core__DOT__imem_enable));
    bufp->fullBit(oldp+84,(vlSelf->top__DOT__dut__DOT__core__DOT__stall_fd));
    bufp->fullIData(oldp+85,(vlSelf->top__DOT__dut__DOT__core__DOT__prev_instr),32);
    bufp->fullIData(oldp+86,(vlSelf->top__DOT__dut__DOT__core__DOT__instr_fd_w),32);
    bufp->fullIData(oldp+87,(vlSelf->top__DOT__dut__DOT__core__DOT__pc4_xm_w),32);
    bufp->fullIData(oldp+88,(vlSelf->top__DOT__dut__DOT__core__DOT__pc4_mw_r),32);
    bufp->fullIData(oldp+89,(vlSelf->top__DOT__dut__DOT__core__DOT__alu_mw_r),32);
    bufp->fullCData(oldp+90,(vlSelf->top__DOT__dut__DOT__core__DOT__funct3_mw_r),3);
    bufp->fullIData(oldp+91,(vlSelf->top__DOT__dut__DOT__core__DOT__data_rs1_stall_w),32);
    bufp->fullIData(oldp+92,(vlSelf->top__DOT__dut__DOT__core__DOT__data_rs2_stall_w),32);
    bufp->fullIData(oldp+93,(vlSelf->top__DOT__dut__DOT__core__DOT__idata1_in),32);
    bufp->fullIData(oldp+94,(vlSelf->top__DOT__dut__DOT__core__DOT__idata2_in),32);
    bufp->fullCData(oldp+95,(vlSelf->top__DOT__dut__DOT__core__DOT__mem_write_access_size),2);
    bufp->fullBit(oldp+96,(vlSelf->top__DOT__dut__DOT__core__DOT__is_store_xm));
    bufp->fullBit(oldp+97,(vlSelf->top__DOT__dut__DOT__core__DOT__wm_forward));
    bufp->fullIData(oldp+98,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem_data_in),32);
    bufp->fullCData(oldp+99,(vlSelf->top__DOT__dut__DOT__core__DOT__mem_read_access_size),2);
    bufp->fullBit(oldp+100,(vlSelf->top__DOT__dut__DOT__core__DOT__is_unsigned));
    bufp->fullIData(oldp+101,(vlSelf->top__DOT__dut__DOT__core__DOT__data_mem_w_sized),32);
    bufp->fullIData(oldp+102,(vlSelf->top__DOT__dut__DOT__core__DOT__al1__DOT__idata1),32);
    bufp->fullIData(oldp+103,(vlSelf->top__DOT__dut__DOT__core__DOT__al1__DOT__idata2),32);
    bufp->fullCData(oldp+104,(vlSelf->top__DOT__dut__DOT__core__DOT__al1__DOT__alu_sel),4);
    bufp->fullIData(oldp+105,(vlSelf->top__DOT__dut__DOT__core__DOT__al1__DOT__odata),32);
    bufp->fullIData(oldp+106,(vlSelf->top__DOT__dut__DOT__core__DOT__al1__DOT__mask),32);
    bufp->fullIData(oldp+107,(vlSelf->top__DOT__dut__DOT__core__DOT__bc1__DOT__idata1),32);
    bufp->fullIData(oldp+108,(vlSelf->top__DOT__dut__DOT__core__DOT__bc1__DOT__idata2),32);
    bufp->fullBit(oldp+109,(vlSelf->top__DOT__dut__DOT__core__DOT__bc1__DOT__br_un));
    bufp->fullBit(oldp+110,(vlSelf->top__DOT__dut__DOT__core__DOT__bc1__DOT__br_eq));
    bufp->fullBit(oldp+111,(vlSelf->top__DOT__dut__DOT__core__DOT__bc1__DOT__br_lt));
    bufp->fullBit(oldp+112,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__clock));
    bufp->fullBit(oldp+113,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__reset));
    bufp->fullBit(oldp+114,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__dx_en));
    bufp->fullBit(oldp+115,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__xm_en));
    bufp->fullBit(oldp+116,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__mw_en));
    bufp->fullCData(oldp+117,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__opcode_dx),7);
    bufp->fullCData(oldp+118,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__opcode_xm),7);
    bufp->fullCData(oldp+119,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__opcode_mw),7);
    bufp->fullCData(oldp+120,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__funct3),3);
    bufp->fullCData(oldp+121,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__funct7),7);
    bufp->fullBit(oldp+122,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__br_eq));
    bufp->fullBit(oldp+123,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__br_lt));
    bufp->fullCData(oldp+124,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rs1_dx),5);
    bufp->fullCData(oldp+125,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rs2_dx),5);
    bufp->fullCData(oldp+126,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rd_xm),5);
    bufp->fullCData(oldp+127,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rd_mw),5);
    bufp->fullCData(oldp+128,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__branch_comp_data1_sel),2);
    bufp->fullCData(oldp+129,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__branch_comp_data2_sel),2);
    bufp->fullBit(oldp+130,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__br_taken));
    bufp->fullBit(oldp+131,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__pc_sel));
    bufp->fullBit(oldp+132,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__br_un));
    bufp->fullCData(oldp+133,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__a_sel),2);
    bufp->fullCData(oldp+134,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__b_sel),2);
    bufp->fullCData(oldp+135,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__alu_sel),4);
    bufp->fullBit(oldp+136,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__mem_rw));
    bufp->fullBit(oldp+137,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__reg_wen));
    bufp->fullCData(oldp+138,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__wb_sel),2);
    bufp->fullBit(oldp+139,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_branch_x));
    bufp->fullBit(oldp+140,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_alu_x));
    bufp->fullBit(oldp+141,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_alu_imm_x));
    bufp->fullBit(oldp+142,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jal_x));
    bufp->fullBit(oldp+143,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_auipc_x));
    bufp->fullBit(oldp+144,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_lui_x));
    bufp->fullBit(oldp+145,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_load_x));
    bufp->fullBit(oldp+146,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_store_x));
    bufp->fullBit(oldp+147,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jalr_x));
    bufp->fullBit(oldp+148,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_x));
    bufp->fullBit(oldp+149,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_u_type_x));
    bufp->fullBit(oldp+150,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__branch_taken));
    bufp->fullBit(oldp+151,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_store_xm_r));
    bufp->fullBit(oldp+152,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_load_xm_r));
    bufp->fullBit(oldp+153,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jal_xm_r));
    bufp->fullBit(oldp+154,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jalr_xm_r));
    bufp->fullBit(oldp+155,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_branch_xm_r));
    bufp->fullBit(oldp+156,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_xm_r));
    bufp->fullBit(oldp+157,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_store_mw_r));
    bufp->fullBit(oldp+158,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_branch_mw_r));
    bufp->fullBit(oldp+159,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_mw_r));
    bufp->fullBit(oldp+160,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_load_mw_r));
    bufp->fullBit(oldp+161,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jal_mw_r));
    bufp->fullBit(oldp+162,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jalr_mw_r));
    bufp->fullBit(oldp+163,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__insn_xm_writes_reg));
    bufp->fullBit(oldp+164,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__insn_mw_writes_reg));
    bufp->fullBit(oldp+165,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_wb));
    bufp->fullBit(oldp+166,(vlSelf->top__DOT__dut__DOT__core__DOT__cs1__DOT__is_nop));
    bufp->fullIData(oldp+167,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__instr),32);
    bufp->fullCData(oldp+168,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__opcode),7);
    bufp->fullCData(oldp+169,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__addr_rd),5);
    bufp->fullCData(oldp+170,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__addr_rs1),5);
    bufp->fullCData(oldp+171,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__addr_rs2),5);
    bufp->fullCData(oldp+172,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__funct3),3);
    bufp->fullCData(oldp+173,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__funct7),7);
    bufp->fullIData(oldp+174,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__imm),32);
    bufp->fullCData(oldp+175,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__shamt),5);
    bufp->fullBit(oldp+176,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_u_type_w));
    bufp->fullBit(oldp+177,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_j_type_w));
    bufp->fullBit(oldp+178,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_i_type_w));
    bufp->fullBit(oldp+179,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_i_shift));
    bufp->fullBit(oldp+180,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_alu));
    bufp->fullBit(oldp+181,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_alu_imm));
    bufp->fullBit(oldp+182,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_load));
    bufp->fullBit(oldp+183,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_store));
    bufp->fullBit(oldp+184,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_branch));
    bufp->fullBit(oldp+185,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_jal));
    bufp->fullBit(oldp+186,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_jalr));
    bufp->fullBit(oldp+187,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_lui));
    bufp->fullBit(oldp+188,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_auipc));
    bufp->fullBit(oldp+189,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_ecall));
    bufp->fullBit(oldp+190,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_r_type));
    bufp->fullBit(oldp+191,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_i_type));
    bufp->fullBit(oldp+192,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_s_type));
    bufp->fullBit(oldp+193,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_b_type));
    bufp->fullBit(oldp+194,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_u_type));
    bufp->fullBit(oldp+195,(vlSelf->top__DOT__dut__DOT__core__DOT__dec1__DOT__is_j_type));
    bufp->fullBit(oldp+196,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__clock));
    bufp->fullBit(oldp+197,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__read_write));
    bufp->fullCData(oldp+198,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__access_size),2);
    bufp->fullIData(oldp+199,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__address),32);
    bufp->fullIData(oldp+200,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__data_in),32);
    bufp->fullIData(oldp+201,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__data_out),32);
    bufp->fullIData(oldp+202,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__addr),32);
    bufp->fullIData(oldp+203,(vlSelf->top__DOT__dut__DOT__core__DOT__dmem1__DOT__i),32);
    bufp->fullBit(oldp+204,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__clock));
    bufp->fullIData(oldp+205,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__address),32);
    bufp->fullIData(oldp+206,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__data_in),32);
    bufp->fullBit(oldp+207,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__read_write));
    bufp->fullBit(oldp+208,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__enable));
    bufp->fullIData(oldp+209,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__data_out),32);
    bufp->fullIData(oldp+210,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__address_2),32);
    bufp->fullIData(oldp+211,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__ea),32);
    bufp->fullIData(oldp+212,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__data_in_2),32);
    bufp->fullBit(oldp+213,(vlSelf->top__DOT__dut__DOT__core__DOT__imem1__DOT__read_write_2));
    bufp->fullBit(oldp+214,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__clock));
    bufp->fullBit(oldp+215,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__write_enable));
    bufp->fullCData(oldp+216,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__addr_rs1),5);
    bufp->fullCData(oldp+217,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__addr_rs2),5);
    bufp->fullCData(oldp+218,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__addr_rd),5);
    bufp->fullIData(oldp+219,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rd),32);
    bufp->fullIData(oldp+220,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs1),32);
    bufp->fullIData(oldp+221,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs2),32);
    bufp->fullIData(oldp+222,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[0]),32);
    bufp->fullIData(oldp+223,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[1]),32);
    bufp->fullIData(oldp+224,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[2]),32);
    bufp->fullIData(oldp+225,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[3]),32);
    bufp->fullIData(oldp+226,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[4]),32);
    bufp->fullIData(oldp+227,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[5]),32);
    bufp->fullIData(oldp+228,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[6]),32);
    bufp->fullIData(oldp+229,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[7]),32);
    bufp->fullIData(oldp+230,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[8]),32);
    bufp->fullIData(oldp+231,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[9]),32);
    bufp->fullIData(oldp+232,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[10]),32);
    bufp->fullIData(oldp+233,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[11]),32);
    bufp->fullIData(oldp+234,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[12]),32);
    bufp->fullIData(oldp+235,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[13]),32);
    bufp->fullIData(oldp+236,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[14]),32);
    bufp->fullIData(oldp+237,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[15]),32);
    bufp->fullIData(oldp+238,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[16]),32);
    bufp->fullIData(oldp+239,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[17]),32);
    bufp->fullIData(oldp+240,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[18]),32);
    bufp->fullIData(oldp+241,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[19]),32);
    bufp->fullIData(oldp+242,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[20]),32);
    bufp->fullIData(oldp+243,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[21]),32);
    bufp->fullIData(oldp+244,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[22]),32);
    bufp->fullIData(oldp+245,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[23]),32);
    bufp->fullIData(oldp+246,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[24]),32);
    bufp->fullIData(oldp+247,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[25]),32);
    bufp->fullIData(oldp+248,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[26]),32);
    bufp->fullIData(oldp+249,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[27]),32);
    bufp->fullIData(oldp+250,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[28]),32);
    bufp->fullIData(oldp+251,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[29]),32);
    bufp->fullIData(oldp+252,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[30]),32);
    bufp->fullIData(oldp+253,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__regs[31]),32);
    bufp->fullIData(oldp+254,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs1_r),32);
    bufp->fullIData(oldp+255,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs2_r),32);
    bufp->fullIData(oldp+256,(vlSelf->top__DOT__dut__DOT__core__DOT__rf1__DOT__i),32);
    bufp->fullIData(oldp+257,(vlSelf->top__DOT__dut__DOT__core__DOT__wb1__DOT__alu),32);
    bufp->fullIData(oldp+258,(vlSelf->top__DOT__dut__DOT__core__DOT__wb1__DOT__pc4),32);
    bufp->fullIData(oldp+259,(vlSelf->top__DOT__dut__DOT__core__DOT__wb1__DOT__mem),32);
    bufp->fullCData(oldp+260,(vlSelf->top__DOT__dut__DOT__core__DOT__wb1__DOT__wb_sel),2);
    bufp->fullIData(oldp+261,(vlSelf->top__DOT__dut__DOT__core__DOT__wb1__DOT__wb_data),32);
}
