// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ top__DOT__clock;
        CData/*0:0*/ top__DOT__clkg__DOT__clk;
        CData/*0:0*/ top__DOT__reset;
        CData/*0:0*/ top__DOT__clkg__DOT__rst;
        CData/*0:0*/ top__DOT__dut__DOT__clock;
        CData/*0:0*/ top__DOT__dut__DOT__reset;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__clock;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__reset;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__fetch_en;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__fd_en;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dx_en;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__xm_en;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__mw_en;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__imem_rw_w;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__opcode_w;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__addr_rd_w;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__addr_rs1_w;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__addr_rs2_w;
        CData/*2:0*/ top__DOT__dut__DOT__core__DOT__funct3_w;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__funct7_w;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__shamt_w;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__is_u_type;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__is_j_type;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__is_i_type;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__reg_wen;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__pc_sel;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__br_un;
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__a_sel;
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__b_sel;
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__branch_comp_data1_sel;
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__branch_comp_data2_sel;
        CData/*3:0*/ top__DOT__dut__DOT__core__DOT__alu_sel;
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__wb_sel;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__br_eq;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__br_lt;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__br_taken;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__data_mem_rw;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__opcode_dx_r;
        CData/*2:0*/ top__DOT__dut__DOT__core__DOT__funct3_dx_r;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__addr_rs1_dx_r;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__addr_rs2_dx_r;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__addr_rd_dx_r;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__funct7_dx_r;
        CData/*2:0*/ top__DOT__dut__DOT__core__DOT__funct3_xm_r;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__opcode_xm_r;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__addr_rs2_xm_r;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__addr_rd_xm_r;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__opcode_mw_r;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__addr_rd_mw_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__is_load_dx;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__is_store_fd;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__is_load_xm;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__is_nop_mw;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__is_nop_xm;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__load_stall;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__instr_mw_writes_reg;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__wd_stall;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__load_store_stall;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__instr_xm_writes_reg;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__store_rs2_stall;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__stall;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__imem_enable;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__stall_fd;
        CData/*2:0*/ top__DOT__dut__DOT__core__DOT__funct3_mw_r;
    };
    struct {
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__mem_write_access_size;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__is_store_xm;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__wm_forward;
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__mem_read_access_size;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__is_unsigned;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__imem1__DOT__clock;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__imem1__DOT__read_write;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__imem1__DOT__enable;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__imem1__DOT__read_write_2;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__opcode;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__addr_rd;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__addr_rs1;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__addr_rs2;
        CData/*2:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__funct3;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__funct7;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__shamt;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_u_type_w;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_j_type_w;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_i_type_w;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_i_shift;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT___opcode;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT___rd;
        CData/*2:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT___funct3;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT___rs1;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT___rs2;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT___funct7;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_alu;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_alu_imm;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_load;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_store;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_branch;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_jal;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_jalr;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_lui;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_auipc;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_ecall;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_r_type;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_i_type;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_s_type;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_b_type;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_u_type;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__is_j_type;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__clock;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__write_enable;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__addr_rs1;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__addr_rs2;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__addr_rd;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__clock;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__reset;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__dx_en;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__xm_en;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__mw_en;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__opcode_dx;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__opcode_xm;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__opcode_mw;
        CData/*2:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__funct3;
        CData/*6:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__funct7;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__br_eq;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__br_lt;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rs1_dx;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rs2_dx;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rd_xm;
        CData/*4:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__addr_rd_mw;
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__branch_comp_data1_sel;
    };
    struct {
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__branch_comp_data2_sel;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__br_taken;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__pc_sel;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__br_un;
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__a_sel;
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__b_sel;
        CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__alu_sel;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__mem_rw;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__reg_wen;
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__wb_sel;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_branch_x;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_alu_x;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_alu_imm_x;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jal_x;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_auipc_x;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_lui_x;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_load_x;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_store_x;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jalr_x;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_x;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_u_type_x;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__branch_taken;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_store_xm_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_load_xm_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jal_xm_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jalr_xm_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_branch_xm_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_xm_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_store_mw_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_branch_mw_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_mw_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_load_mw_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jal_mw_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_jalr_mw_r;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__insn_xm_writes_reg;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__insn_mw_writes_reg;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_ecall_wb;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__is_nop;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT____VdfgTmp_hb2d03f01__0;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__bc1__DOT__br_un;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__bc1__DOT__br_eq;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__bc1__DOT__br_lt;
        CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__alu_sel;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dmem1__DOT__clock;
        CData/*0:0*/ top__DOT__dut__DOT__core__DOT__dmem1__DOT__read_write;
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__dmem1__DOT__access_size;
        CData/*1:0*/ top__DOT__dut__DOT__core__DOT__wb1__DOT__wb_sel;
        CData/*0:0*/ __Vdpi_export_trigger;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__clock__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT__clkg__DOT__clk__0;
        CData/*0:0*/ __VactContinue;
        SData/*11:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT___imm_i;
        SData/*11:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT___imm_s;
        SData/*11:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT___imm_b;
        IData/*31:0*/ top__DOT__genblk1__DOT_____05Ftrace_fd;
        IData/*31:0*/ top__DOT__clkg__DOT__counter;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__pc_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__instr_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__imem_in_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__imm_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__data_rs1_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__data_rs2_w;
    };
    struct {
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__alu_in1_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__alu_in2_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__alu_out_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__data_mem_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__data_rd_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__pc4_f_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__pc_fd_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__pc_dx_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__imm_dx_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__pc_xm_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__imm_xm_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__alu_xm_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__data_rs2_xm_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__pc_mw_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__prev_instr;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__instr_fd_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__pc4_xm_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__pc4_mw_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__alu_mw_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__data_rs1_stall_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__data_rs2_stall_w;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__idata1_in;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__idata2_in;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dmem_data_in;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__data_mem_w_sized;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__imem1__DOT__address;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__imem1__DOT__data_in;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__imem1__DOT__data_out;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__imem1__DOT__address_2;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__imem1__DOT__ea;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__imem1__DOT__data_in_2;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__instr;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__imm;
        IData/*19:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT___imm_u;
        IData/*19:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT___imm_j;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rd;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs1;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs2;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs1_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__data_rs2_r;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__i;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__bc1__DOT__idata1;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__bc1__DOT__idata2;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__idata1;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__idata2;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__odata;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__mask;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dmem1__DOT__address;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dmem1__DOT__data_in;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dmem1__DOT__data_out;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dmem1__DOT__addr;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dmem1__DOT__i;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__wb1__DOT__alu;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__wb1__DOT__pc4;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__wb1__DOT__mem;
        IData/*31:0*/ top__DOT__dut__DOT__core__DOT__wb1__DOT__wb_data;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<IData/*31:0*/, 262144> top__DOT__dut__DOT__core__DOT__imem1__DOT__mem;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__dut__DOT__core__DOT__rf1__DOT__regs;
        VlUnpacked<IData/*31:0*/, 357> top__DOT__dut__DOT__core__DOT__dmem1__DOT__temp;
        VlUnpacked<CData/*7:0*/, 1048576> top__DOT__dut__DOT__core__DOT__dmem1__DOT__mem;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<2> __VicoTriggered;
    VlTriggerVec<4> __VactTriggered;
    VlTriggerVec<4> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*6:0*/ top__DOT__dut__DOT__core__DOT__NOP_OPCODE = 0x13U;
    static constexpr CData/*6:0*/ top__DOT__dut__DOT__core__DOT__LOAD_OPCODE = 3U;
    static constexpr CData/*6:0*/ top__DOT__dut__DOT__core__DOT__STORE_OPCODE = 0x23U;
    static constexpr CData/*6:0*/ top__DOT__dut__DOT__core__DOT__BRANCH_OPCODE = 0x63U;
    static constexpr CData/*6:0*/ top__DOT__dut__DOT__core__DOT__ECALL_OPCODE = 0x73U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__REG = 0U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__PC = 1U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__WX_BYPASS = 2U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__MX_BYPASS = 3U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__IMM = 1U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__BYTE_OP = 0U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__HALF_OP = 1U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__WORD_OP = 2U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__ADD = 0U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__SUB = 1U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__SLL = 2U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__SRL = 3U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__SRA = 4U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__SLT = 5U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__SLTU = 6U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__XOR = 7U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__OR = 8U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__AND = 9U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__NOP = 0x0aU;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__MUL = 0x0bU;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__DIV = 0x0cU;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__DIVU = 0x0dU;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__WB_MEM = 0U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__WB_ALU = 1U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__WB_PC4 = 2U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__REG = 0U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__PC = 1U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__WX_BYPASS = 2U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__MX_BYPASS = 3U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__IMM = 1U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__ADD = 0U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__SUB = 1U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__SLL = 2U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__SRL = 3U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__SRA = 4U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__SLT = 5U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__SLTU = 6U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__XOR = 7U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__OR = 8U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__AND = 9U;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__NOP = 0x0aU;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__MUL = 0x0bU;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__DIV = 0x0cU;
    static constexpr CData/*3:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__DIVU = 0x0dU;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__wb1__DOT__WB_MEM = 0U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__wb1__DOT__WB_ALU = 1U;
    static constexpr CData/*1:0*/ top__DOT__dut__DOT__core__DOT__wb1__DOT__WB_PC4 = 2U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__DATAW = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__BASE_ADDR = 0x01000000U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__ADDRW = 5U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__N_BITS = 5U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__NOP_INSTR = 0x00000013U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__imem1__DOT__START_ADDR = 0x01000000U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__DATAW = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__ADDRW = 5U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__N_BITS = 5U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__IMM_SIZE = 0x0000000cU;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dec1__DOT__IMM_UJ_SIZE = 0x00000014U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__DATAW = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__ADDRW = 5U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__NUM_REGS = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__rf1__DOT__BASE_ADDR = 0x01000000U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__DATAW = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__cs1__DOT__ADDRW = 5U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__bc1__DOT__IDATAW = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__IDATAW = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__al1__DOT__ODATAW = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__dmem1__DOT__BASE = 0x01000000U;
    static constexpr IData/*31:0*/ top__DOT__dut__DOT__core__DOT__wb1__DOT__DATAW = 0x00000020U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
