`include "signals.h"

module design_wrapper (
  // Input to the design
  input wire clock,
  input wire reset,
/*  output [31:0] pc,
  output [31:0] instruction,
  output [31:0] alu_out,
  output br_eq,
  output br_lt,
  output [1:0] branch_comp_data1_sel,
  output [1:0] branch_comp_data2_sel,
  output br_taken,
  output pc_sel,
  output br_un,
  output [1:0] a_sel,
  output [1:0] b_sel,
  output [3:0] alu_sel,
  output mem_rw,
  output reg_wen,
  output [1:0] wb_sel,
  output [6:0] opcode,
  output [4:0] addr_rd,
  output [4:0] addr_rs1,
  output [4:0] addr_rs2,
  output [2:0] funct3,
  output [6:0] funct7,
  output [31:0] imm,
  output [4:0] shamt,
  output is_u_type_w,
  output is_j_type_w,
  output is_i_type_w,
  output [31:0] dmem_data_out,
  output [31:0] imem_data_out,
  output [31:0] data_rs1,
  output [31:0] data_rs2,
  output [31:0] wb_data,
  */
  output [31:0] fd_pc,
  output [31:0] fd_pc4,
  output [6:0] opcode_fd,
  output [4:0] addr_rd_fd,
  output [6:0] opcode_dx,
  output [4:0] addr_rd_dx,
  output [31:0] dx_pc,
  output [31:0] dmem_data_in,
  output [6:0] opcode_xm,
  output [4:0] addr_rd_xm,
  output [31:0] xm_pc,
  output [31:0] wb_in_alu,
  output [31:0] mem,
  output [31:0] mw_pc4,
  output [6:0] opcode_mw,
  output [4:0] addr_rd_mw,
  output [31:0] mw_pc
);
  `TOP_MODULE core(
    .clock(clock),
    .reset(reset),
    /*
    .pc_o(pc),
    .instruction_o(instruction),
    // missing: registers
    .alu_out_o(alu_out),
    .br_eq_o(br_eq),
    .br_lt_o(br_lt),
    .branch_comp_data1_sel_o(branch_comp_data1_sel),
    .branch_comp_data2_sel_o(branch_comp_data2_sel),
    .br_taken_o(br_taken),
    .pc_sel_o(pc_sel),
    .br_un_o(br_un),
    .a_sel_o(a_sel),
    .b_sel_o(b_sel),
    .alu_sel_o(alu_sel),
    .mem_rw_o(mem_rw),
    .reg_wen_o(reg_wen),
    .wb_sel_o(wb_sel),
    .opcode_o(opcode),
    .addr_rd_o(addr_rd),
    .addr_rs1_o(addr_rs1),
    .addr_rs2_o(addr_rs2),
    .funct3_o(funct3),
    .funct7_o(funct7),
    .imm_o(imm),
    .shamt_o(shamt),
    .is_u_type_w_o(is_u_type_w),
    .is_j_type_w_o(is_j_type_w),
    .is_i_type_w_o(is_i_type_w),
    .dmem_data_out_o(dmem_data_out),
    .imem_data_out_o(imem_data_out),
    .data_rs1_o(data_rs1),
    .data_rs2_o(data_rs2),
    .wb_data_o(wb_data),
    */
    .fd_pc_o(fd_pc),
    .fd_pc4_o(fd_pc4),
    .opcode_fd_o(opcode_fd),
    .addr_rd_fd_o(addr_rd_fd),
    .opcode_dx_o(opcode_dx),
    .addr_rd_dx_o(addr_rd_dx),
    .dx_pc_o(dx_pc),
    .dmem_data_in_o(dmem_data_in),
    .opcode_xm_o(opcode_xm),
    .addr_rd_xm_o(addr_rd_xm),
    .xm_pc_o(xm_pc),
    .wb_in_alu_o(wb_in_alu),
    .mem_o(mem),
    .mw_pc4_o(mw_pc4),
    .opcode_mw_o(opcode_mw),
    .addr_rd_mw_o(addr_rd_mw),
    .mw_pc_o(mw_pc)
  );

  endmodule
